language: python
python:
  - "3.3"
  - "3.4"
install: 
  - "pip install -r requirements-testing.txt --use-mirrors"
  - "pip install coveralls"
  - "python setup.py install"
script: 
  nosetests --with-coverage --cover-package=chaser
after_success:
  coveralls
